make data safer by default.in case user delete pvc by accident , and …
hwameistor/hwameistor-operator pull request #289
Opened 2024-07-15 01:54 UTC by peng9808

make data safer by default

2024-07-15 07:27 UTC, peng9808 commented
@SSmallMonster Added helm set storageClassReclaimPolicy=Retain or  Delete...

2024-07-15 12:28 UTC, SSmallMonster requested changes

2024-07-15 12:28 UTC, SSmallMonster commented on helm/operator/templates/hwameistorcluster.yaml
> +    reclaimPolicy: {{ $.Values.storageClassReclaimPolicy }}
values.yaml should look like:
```yaml
storageClass:
  reclaimPolicy: "Retain"
```

2024-07-22 03:19 UTC, SSmallMonster commented on helm/operator/values.yaml
> +  default: false
do operator use `enable` and `default` options now? if not, suggest remove it from values.yaml untill we support indeed.

2024-07-26 07:20 UTC, SSmallMonster approved these changes
lgtm

2024-07-26 07:39 UTC, merged